### ISSUE TITLE
Do not hardcode the URL

### ISSUE THREAD

**Issue by pavelfeldman** [continuationlabs/node-v8-inspector#1]
It'll be changing with each commit. You should fetch it off localhost:5858/json/list instead.

**Comment by cjihrig** [comment]
Ah, thank you. I didn't understand the nature of the link and saw that it was hard coded in core. Just to be clear, `5858` will be whatever the debug port is, correct?

**Comment by pavelfeldman** [comment]
> 5858 will be whatever the debug port is, correct

Yes.

**Comment by cjihrig** [comment]
The URL from the JSON endpoint doesn't seem to do _exactly_ the same thing. My code doesn't seem to be immediately available for debugging.

Node prints:

```
Debugger listening on port 5858.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@521e5b7e2b7cc66b4006a8a54cb9c4e57494a5ef/inspector.html?experiments=true&v8only=true&ws=localhost:5858/node
```

While the JSON endpoint yields: `https://chrome-devtools-frontend.appspot.com/serve_file/@4604d24a75168768584760ba56d175507941852f/inspector.html`

If I replace `https://chrome-devtools-frontend.appspot.com` with `chrome-devtools://devtools/remote`, and then append the same query string (`experiments=true&v8only=true&ws=localhost:5858/node`) it works.

Is this expected behavior, and is it safe to do?

**Comment by pavelfeldman** [comment]
Yes, that schema is pretty conservative. You should parse the hash off the JSON endpoint and use it in the chrome-devtools template. Thanks!
